docs(recursos/open-source: datasets-models): Reorganización de la información en tablas
somosnlp/somosnlp.org pull request #135
Opened 2023-07-07 00:16 UTC by 1-echo

- Referencia a los issues:
  - #41 
  - #42 
- Resumen de cambios:
  - Implementación de una tabla para los recursos datasets.md y models.md con la capacidad de filtrar informacion por columnas.

2023-07-07 00:19 UTC, 1-echo commented
Reviewer: @mariagrandury

2023-07-10 06:46 UTC, mariagrandury requested changes
Muchísimas gracias! :clap: Se me ocurren un par de mejoras. Dependiendo del trabajo que supongan y tu disponibilidad puedes incluir alguna(s) en esta PR y creamos otro(s) issue(s) para el resto.
- Incluir en las etiquetas el dominio de los datasets (e.g., general, clínico, legal)
- Las etiquetas aparecen recuadradas como en la lista anterior (ver imagen)
- Hay una flecha en la primera celda de cada columna que ordena la tabla alfabéticamente (como en la bolsa de empleo). El orden por defecto es alfabético según la columna "Nombre"
- Para que sea más escalable también estaría genial que la tabla tomase los datos de un archivo csv
- No sé si me convence llamar a quien ha subido el dataset/modelo "Usuario HF" pero tampoco se me ocurre algo mejor por ahora

![Screenshot 2023-07-10 081225](https://github.com/somosnlp/somosnlp.org/assets/57645283/3227c0fa-959b-41b1-8f9e-c5cb27b418cc)

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table2.vue
> +useHead({
No hace falta este `useHead`, la página de datasets ya tiene su propia "head"

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table3.vue
> +              <th class="centered-header">Tags</th>
```suggestion
              <th class="centered-header">Etiquetas</th>
```

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table3.vue
> +              <th class="centered-header">Website</th>
```suggestion
              <th class="centered-header">Página web</th>
```

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table2.vue
> +        ¿Echas en falta alguna base de datos? Te animamos a <b>abir una PR</b> <a href="https://github.com/somosnlp/somosnlp.org/edit/main/pages/recursos/open-source/datasets.vue"><u><b>aquí</b></u><
Añadir `target=_blank` para que abra el archivo en una nueva pestaña

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table2.vue
> +        ¿Echas en falta alguna base de datos? Te animamos a <b>abir una PR</b> <a href="https://github.com/somosnlp/somosnlp.org/edit/main/pages/recursos/open-source/datasets.vue"><u><b>aquí</b></u><
Añadir `target=_blank` para que abra el archivo en una nueva pestaña

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table2.vue
> +      <hr class="mx-auto mt-8 mb-12 prose" />
Esta línea de separación al haber creado una tabla ya no es necesaria

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table3.vue
> +        ¿Echas en falta alguna base de datos? Te animamos a <b>abir una PR</b> <a href="https://github.com/somosnlp/somosnlp.org/edit/main/pages/recursos/open-source/datasets.vue"><u><b>aquí</b></u><
Añadir `target=_blank` a continuación de `href`

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table3.vue
> +      <hr class="mx-auto mt-8 mb-12 prose" />
Eliminar bloque `hr`

2023-07-10 06:46 UTC, mariagrandury commented on src/components/Table3.vue
> +useHead({
Eliminar `useHead`

2023-07-10 06:46 UTC, mariagrandury commented on src/components/BlogPost.vue
> +        <article v-if="(frontmatter.title && frontmatter.description && frontmatter.cover) && !(frontmatter.author || frontmatter.duration || frontmatter.date || frontmatter.website || frontmatter.co
Por qué esta diferenciación?

2023-07-10 06:46 UTC, mariagrandury commented on pages/recursos/open-source/datasets.md
> +<Table2
Renombrar a `TableDatasets`

2023-07-10 06:46 UTC, mariagrandury commented on pages/recursos/open-source/modelos.md
> +<Table3
Renombrar a `TableModels`

2023-07-10 06:56 UTC, mariagrandury commented
Btw, si quieres puedes crear un archivo md en `pages/comunidad` con tu nombre para que salgas en la sección de Comunidad 🙌

2023-07-17 09:12 UTC, mariagrandury commented on pages/recursos/open-source/datasets.md
> +<Table2
Me refería a darle un nombre más representativo a `Table2` -> `TableDatasets`. El nombre del archivo `datasets.md` estaba bien para que la url pública sea `somosnlp.org/recursos/open-source/datasets`

2023-07-17 09:13 UTC, mariagrandury commented on pages/recursos/open-source/modelos.md
> +<Table3
Análogo

2023-07-17 09:18 UTC, mariagrandury requested changes
Genial gracias! Un pequeño comentario y listo ✅

2023-07-17 09:18 UTC, mariagrandury commented on src/components/Table3.vue
>                  <div class="tag-cell mx-5">
Para que las etiquetas tengan una separación entre ellas:

```suggestion
                <div class="tag-cell mx-5 flex flex-wrap gap-3">
```

2023-07-17 09:18 UTC, mariagrandury commented on src/components/Table2.vue
>                  <div class="tag-cell mx-5">
Análogo

2023-07-17 09:21 UTC, mariagrandury commented on src/components/BlogPost.vue
> +        <article v-if="(frontmatter.title && frontmatter.description && frontmatter.cover) && !(frontmatter.author || frontmatter.duration || frontmatter.date || frontmatter.website || frontmatter.co
Okey, gracias :) Escribiría un comentario tipo "Para la correcta visualización de las tablas de recursos" para que nos acordemos de la razón

2023-07-17 17:05 UTC, merged

2023-08-02 11:33 UTC, mariagrandury commented
@1-echo FYI ya están creados los follow-up issues :nerd_face: