Add resources from huggingface
somosnlp/somosnlp.org pull request #19
Opened 2022-03-07 18:50 UTC by omarespejel

Agrego dos tutoriales de Hugging Face:
1. Tour del hub
2. Introducción a los demos con Gradio

2022-03-07 19:16 UTC, mariagrandury requested changes
Muchas gracias Omar! Un par de comentarios sobre el YAML header :)

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_ml_demos_con_gradio.md
> +tradducción: @espejelomar
`traducción` no forma parte del los campos actuales del YAML header así que por eso Netlify no consigue construir la página y mostrar una preview.

Puedes ver aquí https://somosnlp.org/resources/notebook_generacion_texto_rap cómo aparece la info del autor.

Para añadir que has hecho tú la traducción podrías escribirlo al final del archivo algo como:
```
---
Traducción del notebook original al español hecha por @espejelomar .
```
y aparecerá justo antes de la info del autor.

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_ml_demos_con_gradio.md
> +title: Creación y hosting de demos de machine learning con Gradio y Hugging Face
El título es mejor que sea más cortito porque al ser la letra tan grande somosnlp.org/resources ocupará 3-4 líneas. La descripción sí puede ser más larga.

Por ejemplo:

```
title: Demos con Gradio y Hugging Face
description: Creación y hosting de demos con Gradio y Hugging Face
```

Mira a ver qué tal queda en la preview cuando arregles el YAML header :)

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_ml_demos_con_gradio.md
> +Por favor ir al notebook original en el [Kit Educativo de Hugging Face](https://github.com/huggingface/education-toolkit/blob/main/tutorials/ES/02_ml-demos-con-gradio.ipynb) o abrir directamente en [
Por qué no convertimos el notebook a .md?

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_tour_hub_huggingface.md
> +description: Introducción al Hub de Hugging Face
La descripción es demasiado parecida al título, igual enumera tres cosas que se explican sobre el Hub, el título me gusta mucho

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_tour_hub_huggingface.md
> +tradducción: @espejelomar
Lo mismo que en el otro notebook

2022-03-07 19:16 UTC, mariagrandury commented on pages/resources/notebook_tour_hub_huggingface.md
> +> En ese tutorial aprenderá a:
Esta parte no debería estar al principio?

2022-03-08 03:33 UTC, omarespejel commented on pages/resources/notebook_tour_hub_huggingface.md
> +> En ese tutorial aprenderá a:
No. Ese fragmento es para presentar el siguiente tutorial sobre demos 🤗 que es el segundo tutorial que subí.

2022-03-08 03:34 UTC, omarespejel commented on pages/resources/notebook_ml_demos_con_gradio.md
> +Por favor ir al notebook original en el [Kit Educativo de Hugging Face](https://github.com/huggingface/education-toolkit/blob/main/tutorials/ES/02_ml-demos-con-gradio.ipynb) o abrir directamente en [
No sé cómo 🙈. Si me das un tip, lo paso jaja

2022-03-08 09:34 UTC, osanseviero commented on pages/resources/notebook_ml_demos_con_gradio.md
> +Por favor ir al notebook original en el [Kit Educativo de Hugging Face](https://github.com/huggingface/education-toolkit/blob/main/tutorials/ES/02_ml-demos-con-gradio.ipynb) o abrir directamente en [
https://reproducible-science-curriculum.github.io/publication-RR-Jupyter/02-exporting_the_notebook/index.html

2022-03-09 06:07 UTC, omarespejel commented
Muchas gracias @mariagrandury @osanseviero ! Listo y andando :D

2022-03-09 09:05 UTC, osanseviero commented
Una pregunta? En vez de duplicar el recurso, no tendría más sentido tener un link al education kit? (no strong opinion, I'll let you guys decide 😄 🚀

2022-03-09 17:07 UTC, mariagrandury commented
Por una parte me parece guay centralizar todos los recursos que vayamos encontrando de NLP en español porque ya he leído un par de veces en Discord que hay pocos recursos y además están desperdigados por ahí (eso sí, siempre poniendo de dónde hemos cogido los recursos).

Por otra parte, si añadimos estos dos notebooks en vez del link al education kit tendremos que crear un artículo cada vez que subáis algo al repo (aunque tampoco se tarda mucho).

Tú qué opinas @omarespejel ?

2022-03-09 18:56 UTC, omarespejel commented
Hola equipo! Tuve vacuna 😅

Concuerdo con @mariagrandury en que es mejor tener todo centralizado! Realmente no es tardado pasar el material y creo que la comunidad también podría estar interesada en colaborar con esto.

2022-03-09 19:06 UTC, mariagrandury approved these changes
Genial! Pues puedes squash los commits en uno que sea algo como `blog: add resources from huggingface` y ya rebase y merge

2022-03-09 20:12 UTC, merged