feat(imágenes_darkmode):
somosnlp/somosnlp.org pull request #228
Opened 2024-03-27 22:05 UTC by 1-echo

- Referencia al Issue #128 
- Resumen de cambios:
    - Modificación al componente "SponsorInfoRouter.vue" para cambiar la imagen de acuerdo al valor de isDark.
    - Creación de un nuevo frontmatter 'cover_dark' que contiene la dirección de la imagen.
    - Modificaciones a los documentos .md de cada patrocinador que posee una imagen para el modo oscuro.

2024-03-30 12:15 UTC, mariagrandury commented
Top @1-echo! Una implementación muy limpia gracias :clap:

Un comentario que sé que es legacy de cómo estaba implementado, creo que es mejor si el fondo de los fondos oscuros es completamente negro como el resto de la página en vez de gray-900, qué opinas?

2024-03-30 12:16 UTC, mariagrandury requested changes
Top @1-echo! Una implementación muy limpia gracias 👏

2024-03-30 12:16 UTC, mariagrandury commented on src/components/SponsorInfoRouter.vue
> +                    dark="bg-gray-900" width="180" height="180"
Sé que es legacy de cómo estaba implementado, creo que es mejor si el fondo de los fondos oscuros es completamente negro como el resto de la página en vez de gray-900, qué opinas?

2024-03-30 20:41 UTC, 1-echo commented on src/components/SponsorInfoRouter.vue
> +                    dark="bg-gray-900" width="180" height="180"
El fondo negro estaría mucho mejor, voy a implementarlo con bg-dark-900 para ver como resulta.

2024-04-01 11:15 UTC, mariagrandury approved these changes
Perfecto, gracias!

2024-04-01 11:15 UTC, merged