Tutorial para aplicar fine-tunning a modelos pre-entrenados
somosnlp/somosnlp.org pull request #28
Opened 2022-03-11 22:35 UTC by yharyarias

Realicé la traducción de training.mdx y me gustaría compartirlo en el repositorio de "somosnlp" para los tutoriales que se van a disponer en la hackathon.

2022-03-13 23:00 UTC, mariagrandury requested changes
Muchas gracias @yharyarias ! Solo una cosilla :)

2022-03-13 23:22 UTC, omarespejel commented
@yharyarias muchas gracias! Apliqué unos ligeros cambios para que funcionará con netlify :). Nada que cambie la estructura.

2022-03-14 03:09 UTC, omarespejel submitted a review, later dismissed
Creo que sería bueno agregar al comienzo que es una traducción de una parte de la documentación de Hugging Face.

2022-03-23 14:14 UTC, omarespejel submitted a review, later dismissed

2022-03-23 14:14 UTC, omarespejel commented on pages/recursos/tutoriales/07_entrenamiento_finetuning.md
> +* Fine-tuning a un modelo pre-entrenado con 🤗 Transformers [`Trainer`](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
```suggestion
* Fine-tuning a un modelo pre-entrenado con 🤗 Transformers `Trainer`(https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
```
Netlify no está logrando aplicar el formato de [`Trainer`] con los []. Por favor quitar los [] de todas las otras palabras que estén en este formato. 

En [esta página](https://deploy-preview-28--somosnlp.netlify.app/recursos/tutoriales/07_entrenamiento_finetuning) puedes ver el preview de cómo se vería tu merge. Nota que no aparecen estas palabras con [``].

2022-03-24 10:33 UTC, mariagrandury commented on pages/recursos/tutoriales/07_entrenamiento_finetuning.md
> +* Fine-tuning a un modelo pre-entrenado con 🤗 Transformers [`Trainer`](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
Creo que en vez de quitar los corchetes [] sería mejor quitar los `` para que quede bien el link así:

[Trainer](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer)

en vez de

`Trainer` (https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer)

2022-03-25 23:52 UTC, omarespejel commented on pages/recursos/tutoriales/07_entrenamiento_finetuning.md
> +* Fine-tuning a un modelo pre-entrenado con 🤗 Transformers [`Trainer`](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
Es cierto. Ya aparece el texto pero no se ve bien por el link. @yharyarias podrías por favor aplicar la sugerencia de @mariagrandury cuando tengas oportunidad?

Gracias!

2022-03-28 21:02 UTC, yharyarias commented on pages/recursos/tutoriales/07_entrenamiento_finetuning.md
> +* Fine-tuning a un modelo pre-entrenado con 🤗 Transformers [`Trainer`](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
Ya mismo lo corrijo. Gracias.

2022-04-01 11:16 UTC, mariagrandury requested changes
Todavía hay problemas con los links, puedes ver una preview de cómo quedaría tu artículo [aquí](https://deploy-preview-28--somosnlp.netlify.app/recursos/tutoriales/07_entrenamiento_finetuning).

En los archivos markdown los links se crean con el texto que quieres que aparezca en corchetes y después el link en paréntesis, i.e.: [texto] (enlace) sin el espacio entre corchetes y paréntesis, e.g.:

[Charlas y talleres del hackathon](https://www.youtube.com/playlist?list=PLTA-KAy8nxaAbVZ2lVcycHnJ2qEDip7hG)

2022-04-21 16:52 UTC, yharyarias commented
Hola @mariagrandury ya quedó corregido el cambio que me sugeriste.

2023-02-20 10:11 UTC, mariagrandury approved these changes

2023-02-20 10:26 UTC, merged