Mi perfil profesional como colaboradora - yharyarias
somosnlp/somosnlp.org pull request #33
Opened 2022-03-21 20:30 UTC by yharyarias

Hola equipo de Somos NLP, acabo de añadir mi información  como colaboradora.
@mariagrandury @omarespejel

2022-03-22 13:28 UTC, osanseviero commented
Hola! En el log del PR hay commits que parecen ser de otro contribuidor y en el diff de archivos tambien. Lo mismo paso en https://github.com/huggingface/transformers/pull/16299. Creo que estas usando un branch en el que habia otros cambios, idealmente deberias estar en un branch limpio (es decir, ir a main, hacer pull, luego hacer checkout, hacer los cambios, hacer push), en vez de hacer los cambios desde un branch con otros cambios. Seria genial si puedes hacer el cambio en ambos PRs para hacerle merge

2022-03-22 17:01 UTC, yharyarias commented
Claro que si @osanseviero, ya mismo lo hago,

2022-03-24 01:38 UTC, yharyarias commented
@osanseviero cuales son las reglas para cerrar un pull request? Para volver a crear uno y enviar todo en limpio.

2022-03-24 08:28 UTC, osanseviero commented
No hay ninguna regla :smile: puedes eliminar los cambios no relacionados con el PR, es decir, [07_entrenamiento_finetuning.md](https://github.com/somosnlp/somosnlp.org/pull/33/files#diff-689d1d00e97f39fdecf468edf16d1b5b8d89d4ed5e7dd08f1bb92feadb4f9150), o puedes abrir un nuevo PR, pero idealmente en este PR esta bien.

Cuando hagamos el merge, podemos dar "Squash and merge", por lo que el commit history estara limpio

2022-03-24 10:26 UTC, mariagrandury requested changes
A parte de separar estos cambios de los del tutorial como dijo Omar y el detalle de tu bio, perfecto :)

2022-03-24 10:26 UTC, mariagrandury commented on pages/core-team/yhary-arias.md
> +title: Data Engineer, Master's student in AI at the UPV
Para que sea coherente con el resto de bios del equipo :)

```suggestion
title: Data Engineer | Master's student in AI @UPV
```

2022-03-24 10:30 UTC, mariagrandury commented
@yharyarias para la próxima vez, creo que lo que te pasó fue que creaste esta rama estando en la del tutorial (en vez de en `main`). Pero no pasa nada, haz lo que te dijo Omar y hacemos squash antes de merge :)

2022-04-01 11:08 UTC, mariagrandury approved these changes
Genial, bienvenida al equipo!

2022-04-01 11:09 UTC, merged